# Robot Configuration Parameters
TrajectoryPlannerROS:
    acc_lim_x: 0.8
    acc_lim_y: 0.8
    acc_lim_theta: 1.5
    acc_limit_trans: 0.4
    max_vel_x: 0.5
    min_vel_x: 0.1
    max_vel_y: 0.3
    min_vel_y: 0.1
    max_rotational_vel: 0.75
    min_in_place_rotational_vel: 0.1
    escape_vel: -0.1
    holonomic_robot: true
    y_vels: -0.3

    # Goal Tolerance Parameters
    xy_goal_tolerance: 0.05
    yaw_goal_tolerance: 0.1

    # Forward Simulation Parameters
    sim_time: 1.7
    sim_granularity: 0.025
    sim_period: 0.3
    stop_time_buffer: 0.3
    vx_samples: 6
    vy_samples: 8
    vtheta_samples: 6

    # Trajectory Scoring Parameters
    goal_distance_bias: 5.0
    path_distance_bias: 0.9
    occdist_scale: 0.01
    heading_lookahead: 0.3
    dwa: true

    # Oscillation Prevention Parameters
    oscillation_reset_dist: 0.1

    penalize_negative_x: false
