footprint: [[0.285, 0.225], [0.375, 0.075], [0.375, -0.075], [0.285, -0.225], [-0.285, -0.225], [-0.285, 0.225]]

recovery_behavior_enabled: true
controller_frequency: 10.0
controller_patience: 3.0
clearing_radius: 0.4
clearing_rotation_allowed: false
oscillation_distance: 1.0
footprint_padding: 0.0
recovery_behaviors:
  - name: 'conservative_reset'
    type: 'clear_costmap_recovery/ClearCostmapRecovery'
  - name: 'aggressive_reset'
    type: 'clear_costmap_recovery/ClearCostmapRecovery'
base_global_planner: global_planner/GlobalPlanner
GlobalPlanner:
    use_grid_path: False
    use_dijkstra: True
    allow_unknown: False
    default_tolerance: 0.5
    visualize_potential: False
    use_quadratic: True
    old_navfn_behavior: False
base_local_planner: dwa_local_planner/DWAPlannerROS


